# Generated by Django 4.2.6 on 2023-10-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=45, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('rh', models.CharField(choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH')),
                ('posicion', models.CharField(choices=[('PT', 'Portero'), ('DC', 'Defensa Central'), ('DL', 'Defensa Lateral'), ('DLI', 'Defensa Libre'), ('CC', 'Centrocampista'), ('CCD', 'Centrocampista Defensivo'), ('CCO', 'Centrocampista Ofensivo'), ('EXT', 'Extremo'), ('DEL', 'Delantero')], max_length=3, verbose_name='Posicion')),
            ],
        ),
    ]
