# Generated by Django 4.2.6 on 2023-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
